export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",
  INVALID_FIELD_FORMAT: "INVALID_FIELD_FORMAT",
  INVALID_CREDENTIAL: "INVALID_CREDENTIAL",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  TIMESTAMP_EXPIRED: "TIMESTAMP_EXPIRED",
  NONCE_REPLAYED: "NONCE_REPLAYED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
